# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-20 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
